FROM node:23-alpine3.20

WORKDIR /usr/src/app

RUN apk add --no-cache bash

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build  # Create optimized production build

EXPOSE 3000

CMD ["npx", "serve", "-s", "build", "-l", "3000"]  # Serve the build folder
